### PR TITLE
Fix/dev to rails4 branch merge specs

### PR DESCRIPTION
**Pull request by ulferts**
Should fix two of the specs failing on https://github.com/opf/openproject/pull/3327. 

However, I had to bump database cleaner in order to get one spec to work and I am unsure yet, as of how much havoc this will cause.

### CODE REVIEW

**Comment by myabc** [comment]
@ulferts thanks for this. Unfortunately, PostgreSQL is complaining with a `SQLError`.

**Comment by ulferts** [comment]
I'll give it another look today.

**Comment by ulferts** [comment]
@myabc everything is green now. Could you please merge so I can merge opf#3327 in?

**Comment by myabc** [comment]
@ulferts ok. merged

**Comment by ulferts** [comment]
Thanks @myabc.

**Pull request merged**
